# Generated by Django 6.1 on 2026-08-21 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medical_record_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.FloatField(null=True)),
                ('sex', models.FloatField(null=True)),
                ('cp', models.FloatField(null=True)),
                ('trestbps', models.FloatField(null=True)),
                ('chol', models.FloatField(null=True)),
                ('fbs', models.FloatField(null=True)),
                ('restecg', models.FloatField(null=True)),
                ('thalach', models.FloatField(null=True)),
                ('exang', models.FloatField(null=True)),
                ('oldpeak', models.FloatField(null=True)),
                ('slope', models.FloatField(null=True)),
                ('ca', models.FloatField(null=True)),
                ('thal', models.FloatField(null=True)),
                ('result', models.IntegerField(choices=[(0, 'Low Risk'), (1, 'High Risk')], null=True)),
                ('probability', models.FloatField(help_text='Model confidence score (0-1)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Clinical notes for this assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='predictor.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
