# Generated by Django 6.0.1 on 2026-01-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.FloatField(null=True)),
                ('sex', models.FloatField(null=True)),
                ('cp', models.FloatField(null=True)),
                ('trestbps', models.FloatField(null=True)),
                ('chol', models.FloatField(null=True)),
                ('fbs', models.FloatField(null=True)),
                ('restecg', models.FloatField(null=True)),
                ('thalach', models.FloatField(null=True)),
                ('exang', models.FloatField(null=True)),
                ('oldpeak', models.FloatField(null=True)),
                ('slope', models.FloatField(null=True)),
                ('ca', models.FloatField(null=True)),
                ('thal', models.FloatField(null=True)),
                ('result', models.IntegerField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
